### ISSUE TITLE
Cookie test

### ISSUE THREAD

**Issue by dareid** [dareid/chakram#18]
Add a new cookie test, demonstrating use of cookies across multiple requests. Demonstrates the capability for new users and ensure it works correctly.

**Comment by filso** [comment]
hi @dareid, I'm trying to set this thing up to preserve cookies in between requests. The problem is I can't set default `jar` option with `chakram.setRequestDefaults` to anything because of these lines: 
```
exports.request = function (method, url, params) {
    var options = extend({
        url: url,
        method: method,
        json: true,
        jar: request.jar()
    }, params || {} );
    var deferred = Q.defer();
    var reqObj = defaultedRequestObj || request;
    reqObj(options, function (error, response, body) {
```
`request.jar` will take priority over default request options, therefore the only way to use my jar is to add `{jar: j}` (or `{jar: true}`) to each request options

**Comment by dareid** [comment]
Glad you are finding the library useful. 
Good catch. The PR would be amazing if you had time - thanks for the kind offer!

**Comment by filso** [comment]
https://github.com/dareid/chakram/pull/23
