### ISSUE TITLE
Chakram won't let me check json if in new line

### ISSUE THREAD

**Issue by ferylukacs** [dareid/chakram#86]
a simple code like:

return chakram.get(url).then(fucntion(check){
expect(check)to.have.json({[username: 'x', firstName: 'xx', lastName: "lastname"]})
return chakram.wait(); //because i do other stuff in the code also
});

i was wondering whi it won't let me check liek this: 
expect(check)to.have.json({[
username: 'x', 
firstName: 'xx', 
lastName: "lastname"]})

It vould be userful for my tests that have 10+ items to check. I tried to put the parentheses down, up , whatever, it gives me a red X on return. 

Any suggestions? thanks

**Comment by dareid** [comment]
I am a little confused with your question. But something I have noticed is that your code snippets have invalid json.

So 
```
{[
  username: 'x',
  firstName: 'xx',
  lastName: "lastname"
]}
```
should probably be 
```
{
  username: 'x',
  firstName: 'xx',
  lastName: "lastname"
}
```

**Comment by ferylukacs** [comment]
yes, that's beenm corrected already, but still, it gives me a red X on return when i press enter before Username..

**Comment by ferylukacs** [comment]
The only thing i can do, is to put this in a new line 

expect(check)to.have.json(
{username: 'x', firstName: 'xx', lastName: "lastname"});

**Comment by harryrose** [comment]
Hi, @ferylukacs.  Please could you paste the error message, and the test you're trying to run (assuming it doesn't contain anything sensitive of course).  Newline characters shouldn't be making a difference to your test.

**Comment by ferylukacs** [comment]
It gives me a red x, on the "return chakram wait..." line, in eclipse, i am.not running the test.

**Comment by harryrose** [comment]
aha.  sorry, I understand now, i thought you meant you get a red x saying the test had failed :).  It has been a while since I used eclipse, but I think if you hover over the x, it should show a tooltip describing the problem.  If not, then there's a "Problems" tab, which should contain the error's description.

I don't think this is likely to be an issue with Chakram.  Most likely there's a syntax error or undefined variable in the test.  Based on your comment 4 hours ago, one thing to check is that you have a `.` between `expect(check)` and `to`.

**Comment by dareid** [comment]
I am going to close this as it sounds like a syntax error.

**Comment by ferylukacs** [comment]
Yes, the . is ok, it was not a copy paste, The thing is that if i leave in in one line, the test runs flawlessly, but when adding to new lines, the problem occurs. But if this ain't a problem from your side, i will try to resolve it here.
